### ISSUE TITLE
Alpine mongodb package no longer exists

### ISSUE THREAD

**Issue by hikaruichijo** [mvertes/docker-alpine-mongo#16]
This package is no longer listed in the edge repository, so docker build fails.

**Comment by mvertes** [comment]
I just updated Dockerfile and rebuilt image. Let me know if docker build still fails.

**Comment by bautze** [comment]
I am having the same issue. mongodb does not exist for alpine:edge. build fails.

**Comment by mvertes** [comment]
package was moved from `testing` to `community` in alpine. Not an issue anymore.
