### ISSUE TITLE
MongoDB shell error

### ISSUE THREAD

**Issue by franz-josef-kaiser** [mvertes/docker-alpine-mongo#2]
When accessing the container via 

    docker exec -it mongodb /bin/sh

and executing just `mongo` or any of the provided [cli/shell functions](https://docs.mongodb.org/manual/reference/mongo-shell/), I get the following error:

```shell
/ # mongo --verbose
MongoDB shell version: 3.2.1
too much recursion
2016-02-14T21:49:01.670+0000 D -        [thread1] User Assertion: 139:Failed to initialize JSContext
2016-02-14T21:49:01.690+0000 D -        [main] User Assertion: 139:Failed to initialize JSContext
exception: Failed to initialize JSContext
```

**Update:** Above `mongo` command now with `--verbose` flag.

After some searching to see if I can find the source of this error, I found the following definition:

> **Objective-C** – `JSContext` is an environment for running JavaScript code. A `JSContext` instance represents the global object in the environment—if you’ve written JavaScript that runs in a browser, `JSContext` is analogous to `window`. _Source: [NSHipster](http://nshipster.com/javascriptcore/)_

Going down the rabbit hole, I looked up what an _Assertion_ is in Objective-C and found that it throws an Exception in case the assertion fails. I'm assuming that the `too much recursion` error happened first and caused the program to break. As I saw that the first error is actually an [Internal Error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError) in the JavaScript core, I now assume that there's some internals broken and not the JSContext not being available in Alpine in this scenario.

Found a similar error in the following repo/issue: gliderlabs/docker-alpine#137 (cross referenced).

**Comment by mvertes** [comment]
Raised a bug upstream: http://bugs.alpinelinux.org/issues/5117
