### ISSUE TITLE
Does this container need an init system?

### ISSUE THREAD

**Issue by halfer** [mvertes/docker-alpine-mongo#21]
As a matter of course, I have been adding [this init system](https://github.com/Yelp/dumb-init) into my container Dockerfiles. Without an init system, they were previously slow to stop, and I found the reason was that gentle kill signals were not working, and so Docker was forced to resort to more aggressive kills to stop such containers.

I have found that `mvertes/alpine-mongo` is also slow to stop, and presume that the same reason applies. Should, and can, an init system be added? I may do this myself in my inheriting Dockerfile, but it seems sensible to do this upstream if possible.

**Comment by mvertes** [comment]
Sorry for the late response. It appears that `docker stop` on this image (version 3.6.4-2 now) works instantaneously (image started as explained in readme). Nothing more required.

**Comment by halfer** [comment]
Thanks! I had forgotten I had raised this. From what I have learned recently, I think it does not need it because the command executes the Mongo binary directly. If it were to invoke a shell script which then invokes Mongo, it would need an init system because the shell script would not reliably pass on signals to the binary itself.
