### ISSUE TITLE
is there plan for 3.6 build ?

### ISSUE THREAD

**Issue by Meabed** [mvertes/docker-alpine-mongo#22]
is there plan for 3.6 build ?
Thanks

**Comment by mvertes** [comment]
Yes, porting mongodb-3.6.1 to alpinelinux right now. Docker image will be updated when integrated in alpine ports.

**Comment by mvertes** [comment]
Port of 3.6 is now part of alpinelinux. Closing this issue

**Comment by Meabed** [comment]
Thank you!
