### ISSUE TITLE
Add bind_ip option for 3.6 version.

### ISSUE THREAD

**Issue by tarhan** [mvertes/docker-alpine-mongo#24]
As stated in logs messages and in [Upgrade a Standalone to 3.6](https://docs.mongodb.com/manual/release-notes/3.6-upgrade-standalone/) mongod by default now binded at 127.0.0.1 which is make it not visible outside of Docker (does not case for Kubernetes).
So I suggest to lauch mongo (in ```run.sh```) as
```
mongod --bind_ip 0.0.0.0
```
by default to be consistent with previous version of your docker image.

**Comment by mvertes** [comment]
Thanks for the report and the suggestion. I will do as you propose.

**Comment by tarhan** [comment]
You welcome
