### ISSUE TITLE
Upgrade to 3.6.3

### ISSUE THREAD

**Issue by Meabed** [mvertes/docker-alpine-mongo#25]
Hey @mvertes thank you for the image,

Could you upgrade the image to v 3.6.3

there is a new release in mongo and it has some new features and it fix alot of issues, please have a look here https://docs.mongodb.com/manual/release-notes/3.6-changelog/#id1

let me know i could help.

Thanks

**Comment by mvertes** [comment]
I submitted the upgrade patch to 3.6.3 to alpinelinux upstream. I will update the image when applied.

**Comment by mvertes** [comment]
Commit 43993fbbee0f21bf168a8d0b3a13c713ebc83ff9  fixes this issue
