### ISSUE TITLE
Image with 3.6.4-0 fails to start

### ISSUE THREAD

**Issue by yegorius** [mvertes/docker-alpine-mongo#26]
The latest version upgrade to `3.6.4-0` breaks the container.
Log output:
```
E STORAGE  [initandlisten] WiredTiger error (22) [1523880149:173900][1:0x7fd16a8debd0], wiredtiger_open: unknown configuration key: 'cache_cursors': Invalid argument
```

**Comment by mvertes** [comment]
Patch submitted to alpine upstream: http://lists.alpinelinux.org/alpine-aports/5353.html
Will update image ASAP.
