### ISSUE TITLE
mongo 4.0.0 image 

### ISSUE THREAD

**Issue by anmolnagpal** [mvertes/docker-alpine-mongo#27]
Hello @mvertes When you are planning to push mongo 4.0.0

**Comment by mvertes** [comment]
Hopefully next weekend I will  attempt the upgrade of mongodb on alpine-linux. Image should arrive a few days later, when patches will be applied in mainline

**Comment by anmolnagpal** [comment]
Thank You

**Comment by AlfieriChou** [comment]
Thanks

**Comment by Meabed** [comment]
Thanks @mvertes :) do you need a hand here? 👍

**Comment by mvertes** [comment]
Closing, following c65b379d13ff1361d9ff4349260cc927f0eadc8a
