### ISSUE TITLE
Crashes on collection.drop()

### ISSUE THREAD

**Issue by raeesiqbal** [mvertes/docker-alpine-mongo#3]
Hey there, I'm trying to use this mongo container but it will crash everytime I do a `drop()` on a collection.
Here is how to to repro:
```
> use mydb
switched to db mydb
> db.some.insertOne({'ding' : 'dong'});
{
	"acknowledged" : true,
	"insertedId" : ObjectId("56d17d0fa673ea32ea9117a5")
}
> db.some.drop();
```

**Comment by mvertes** [comment]
Yes. I'm working on a fix upstream, almost ready. see also http://bugs.alpinelinux.org/issues/5188

Thanks

**Comment by raeesiqbal** [comment]
Good, thanks

**Comment by mvertes** [comment]
My fix has been merged: http://git.alpinelinux.org/cgit/aports/commit/?id=511d407ad2dd4fbbc5f259fb729274dc4871dea0
I triggered rebuild of images on https://hub.docker.com/r/mvertes/alpine-mongo

**Comment by raeesiqbal** [comment]
Working as expected. Thanks
