### ISSUE TITLE
How do I pass command line options to mongod

### ISSUE THREAD

**Issue by nevf** [mvertes/docker-alpine-mongo#5]
Apologies if this is a stupid question however I can't see a way to pass command line options to mongod. ex. `docker ....  mvertes/alpine-mongo --smallfiles` gives `/run: exec: line 3: --smallfiles: not found`

I am using Docker on Windows and am not a Linux guy and am new to Docker. Best I can work out is this is an issue with the `run` script.

**Comment by mvertes** [comment]
Hello,
You simply need to provide the program name before the arguments:
```docker run <docker_options...> mvertes/alpine-mongo mongod --smallfiles```

**Comment by nevf** [comment]
@mvertes Thanks so much, that was simple enough.

How do you connect another container to the container running Mongodb. I tried Docker Networking and failed. I also tried Docker linking but couldn't get that to work either. Right now I'm using the IP address of the host? for the Mongo connect call, which works but is messy.
