### ISSUE TITLE
Does this build support TLS/SSL connections

### ISSUE THREAD

**Issue by Bochenski** [mvertes/docker-alpine-mongo#8]
I'm trying to configure SSL connectivity, but I get the following error:

`Unrecognized option: net.ssl.mode` when I try to start `mongod` pointing to a config file with ssl enabled.

Do you know whether the underlying mongod binary was compiled with ssl support?

**Comment by mvertes** [comment]
Underlying mongod could not be compiled using SSL support on alpinelinux. I would like to fix it as soon as I can, but it will not be before next week.

**Comment by barbarello** [comment]
Hi Marc,

Any idea when you'll fix this ?

Thanks.

**Comment by mvertes** [comment]
I'm on this right, so quite soon I hope

**Comment by mvertes** [comment]
I submitted this patch: http://lists.alpinelinux.org/alpine-aports/3514.html to alpinelinux
When applied,  I will update the docker image.
